---

- name:  "Add Node.js from source"
  become: true
  shell: |
    curl -sl https://deb.nodesource.com/setup_17.x | sudo -E bash -
- name: install node.js 17
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    # state: latest
    # production: yes

- name:  "Move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/